// MazoLogic v3b — Bilingual strings (TypeScript module)
// Converted from v3b-strings.js

export const STRINGS = {
  en: {
    nav: { method: "Method", process: "Process", infra: "Any Infrastructure", cta: "Book a free audit →" },
    hero: {
      eyebrow: "Free · 30 minutes · No strings attached",
      h1a: "Your business runs in 12 places.",
      h1b: "Time to give it one voice.",
      sub: "Your CRM says one thing. Your spreadsheet says another. Your team asks Slack. We don't replace your stack — we connect it, give it memory, and let you talk to the whole thing at once.",
      h1variants: [
        { h1a: 'Your business runs in <span style="color:#6fa8d4">12 places.</span>', h1b: "Time to give it one voice.", sub: "Your CRM says one thing. Your spreadsheet says another. Your team asks Slack. No one has the full picture — and every decision costs time. We don't replace your stack. We connect it, give it memory, and let you talk to the whole thing at once." },
        { h1a: 'Stop chasing data <span style="color:#6fa8d4">across tools.</span>', h1b: "Start talking to your business.", sub: "You keep the tools you know. We add the layer that makes them talk to each other — and to you. One conversation replaces eight browser tabs." },
        { h1a: 'Spreadsheets. Dashboards. Slack threads. <span style="color:#6fa8d4">Gut feeling.</span>', h1b: "There's a better way to run a business.", sub: "These tools aren't the problem. The gaps between them are. We plug in on top of what you already have — and fill every gap with automation." },
        { h1a: 'Your team spends hours connecting dots <span style="color:#6fa8d4">that should connect themselves.</span>', h1b: "We automate the dots. You run the business.", sub: "The dots are already there. The data exists. We build the system that connects it automatically — no migration, no disruption, no \"we need to switch everything.\"" },
        { h1a: 'Your processes are scattered. <span style="color:#6fa8d4">Your data is silent.</span>', h1b: "We fix both.", sub: "Nothing gets thrown away. We plug into your existing stack, unify what's already there, and give you one place to see and steer it all." },
      ],
      cta: "Book a free audit →",
      chip1: "Completely free",
      chip2: "Only 30 minutes",
      chip3: "You'll see exactly where AI saves you time or money",
      vp1: "Find your revenue gap",
      vp2: "Identify your one biggest bottleneck",
      vp3: "Get your AI implementation roadmap",
    },
    method: {
      eyebrow: "How we work",
      h2a: "We don't add another tool",
      h2b: "on top of your stack.",
      lead: "We start by understanding exactly how your business operates. Then we build one unified system that simplifies the complexity, connects what you already have, and gets out of your team's way.",
      card1h: "Map your operations",
      card1p: "We begin with a structured audit — not assumptions. We learn how your business actually runs, identify where complexity compounds, and model the ROI of simplifying it before a single line of code is written.",
      card1tag: "→ Architecture Audit · Process map · ROI estimate",
      card2h: "Unify into one system",
      card2p: "We connect your tools, consolidate your data, and train an AI on your business context — your clients, your history, your language. One source of truth. One system that already knows the answer.",
      card2tag: "→ SSOT · Context layer · Agents wired to your stack",
      card3h: "Hand over control",
      card3p: "You get one interface to run your operations. Issue a command, get a result. No dashboards to maintain, no manual entry. The system handles the complexity. You steer.",
      card3tag: "→ Documented · Trained · Yours to keep",
    },
    solution: {
      eyebrow: "What you get",
      h2a: "A system built for your business.",
      h2b: "Not a template. Not a chatbot.",
      card1h: "Single Source of Truth",
      card1p: "All your business data — clients, revenue, projects, history — in one place your AI can actually use. No more hunting across systems.",
      card1tag: "→ CRM · Database · Clean data layer",
      card2h: "Agents that reason",
      card2p: "Automations that don't just trigger — they think. Built on your mapped processes, not generic if-then rules.",
      card2tag: "→ Telegram · Email · Reports · Scheduling",
      card3h: "Delivered and documented",
      card3p: "Full handover. Your team gets trained, the system is documented, and you own everything — no ongoing dependency on us.",
      card3tag: "→ Trained · Documented · Yours",
    },
    spotlight: { left: "Ready to deploy your", right: "AI Operating System?" },
    matrix: {
      eyebrow: "Architecture Audit",
      h2a: "Before we build:",
      h2b: "a clear picture of what's worth automating.",
      lead: "We map your operations into four zones — ranked by cost, effort, and return. You leave knowing exactly where AI pays back, and what to ignore.",
      axisHigh: "High impact", axisLow: "Low impact",
      axisEffortLow: "Low effort →", axisEffortHigh: "High effort",
      q1tag: "Quick wins", q1title: "Quick Wins", q1desc: "Fast time recovery. Deploy in 2–3 weeks, measurable payback by week 4.", q1foot: "01 · start here",
      q2tag: "Strategic", q2title: "AI OS Core", q2desc: "High-leverage systems. The foundation everything else runs on.", q2foot: "02 · AI OS core",
      q3tag: "Fill-ins", q3title: "Tune later", q3desc: "Small recurring tasks. Worth automating once the core is stable.",
      q4tag: "Avoid", q4title: "Defer", q4desc: "High effort, low return. Document, park, and revisit.",
    },
    process: {
      eyebrow: "Implementation roadmap",
      h2a: "Four phases.", h2b: "Audit to handover.",
      phases: [
        { num: "PHASE 01", h: "Audit",    p: "A structured 30-minute session for SMBs, or 1–2 days on-site for larger organisations. You leave with an Impact-Effort Matrix and a clear scope." },
        { num: "PHASE 02", h: "Build",    p: "We connect your data sources, clean your information layer, and train the AI on your business context — clients, history, and language." },
        { num: "PHASE 03", h: "Tune",     p: "14-day live calibration. We monitor every action, fine-tune the agent's logic, and push accuracy past 95% before handover." },
        { num: "PHASE 04", h: "Handover", p: "Full transfer: trained AI system, complete documentation, and a walkthrough session so your team runs it independently from day one." },
      ],
    },
    infra: {
      eyebrow: "Any infrastructure",
      h2a: "Your stack stays.", h2b: "We build on top of it.",
      lead: "You don't need to replace your CRM, your spreadsheets, or your existing tools. We layer the AI OS on top of what you already have — connecting, unifying, and extending it.",
    },
    scorecard: {
      eyebrow: "Operations Diagnostic",
      h2a: "Where is your business losing time,",
      h2b: "and what could work better?",
      lead: "15 questions. We'll show you exactly where AI fits — and where it doesn't.",
    },
    gate: {
      title: "Where should we send your results?",
      sub: "We'll email you a personalised AI implementation roadmap based on your answers.",
      name: "Your name", email: "Work email",
      cta: "Book a free audit →",
      privacy: "No spam. Your results stay private. Unsubscribe anytime.",
    },
    q:   { no: "No — everything lives in people's heads", partial: "Partially — some things are written down", yes: "Yes — most processes are documented" },
    q1:  { q: "Does your business have documented, repeatable processes for routine tasks (onboarding, invoicing, follow-ups)?" },
    q2:  { q: "Is your company data centralised in one system (CRM, database, or shared tool)?", a: "No — data lives in emails, spreadsheets, and messages", b: "Partly — we have a CRM but it's not consistently used", c: "Yes — we have a central system everyone uses" },
    q3:  { q: "Are any repetitive administrative tasks currently automated (reminders, reports, data entry)?", a: "No — everything is done manually", b: "Some — we use basic tools like Zapier or scheduled reports", c: "Yes — multiple workflows are automated" },
    q4:  { q: "Does your team regularly use AI tools (ChatGPT, Claude, Copilot) in daily work?", a: "No — AI isn't part of our workflow yet", b: "Occasionally — a few people use it here and there", c: "Yes — AI is a regular part of how we work" },
    q5:  { q: "Does your business use a unified communication platform where tasks and decisions are tracked?", a: "No — we rely on email and phone calls", b: "We use messaging apps but not consistently", c: "Yes — we have a unified platform for communication" },
    q6:  { q: "Is there a system that automatically follows up with leads or clients?", a: "No — follow-ups depend on people remembering", b: "Basic — we have some reminders set up manually", c: "Yes — follow-ups are automated in our CRM" },
    q7:  { q: "Can you get a clear business performance report without manually pulling data from multiple systems?", a: "No — we build reports manually, takes hours", b: "Partly — some data is automatic, some manual", c: "Yes — dashboards update automatically" },
    q8:  { q: "Does your business have documented policies for data privacy and how AI tools can be used?", a: "No — no formal policies exist", b: "Informally — there are unwritten rules", c: "Yes — formal documented policies are in place" },
    q9:  { q: "Does your business have a clear plan for where AI should be implemented in the next 12 months?", a: "No — we're reacting as AI comes up", b: "Loosely — we have ideas but nothing documented", c: "Yes — we have a documented AI roadmap" },
    q10: { q: "Is there a dedicated budget allocated for AI implementation in your business?", a: "No — no budget exists for this", b: "We pay for some SaaS tools but no dedicated AI budget", c: "Yes — we have a dedicated budget for AI" },
    q11: { q: "Which best describes your current AI adoption level?", a: "Haven't started — AI is still on the 'to explore' list", b: "Experimenting — we've tried some tools with mixed results", c: "Adopting — AI is in use but not yet deeply integrated" },
    q12: { q: "What is your primary goal for the next 90 days?", a: "Save 10+ hours of team time per week", b: "Increase leads and close more deals", c: "Reduce errors and manual data entry", d: "Build a competitive AI advantage in my industry" },
    q13: { q: "What is the biggest thing stopping you from scaling AI right now?", a: "Technical complexity — I don't know where to start", b: "Time — no capacity to research and implement", c: "Budget concerns — unclear if the ROI is there", d: "Finding the right partner who actually delivers" },
    q14: { q: "Which solution suits you best?", a: "Self-service — I want training and resources to build it myself", b: "Guided — I want a consultant to help me choose and set up tools", c: "Done-for-you — I want a complete AI OS built and deployed for my business" },
    q15: { q: "Is there anything specific about your business we should know? (optional)", cta: "Book a free audit →" },
    results: { insightsTitle: "Your personalised insights" },
    caseStudy: {
      eyebrow: "Live · Deployed · Running",
      h2a: "One agent.", h2b: "One OS. 19 tools.",
      h3a: "Agency owner types one message.", h3b: "The system handles the rest.",
      p: "An AI assistant with 19 tools — connected to Airtable CRM, email, voice messages, and web scraping — executes complex multi-step tasks from a single Telegram message.",
      stat1label: "tools connected", statSwitch: "app switches",
      demoLabel: "Live interaction — Telegram",
      ownerMsg: "Find potential buyers for the property on Maple Street. Send them all an SMS that there's a new property matching their criteria. Also send them an email. Finally confirm with a voice message that everything is done.",
      step1: "Searched Airtable — 7 matching buyers found",
      step2: "7 personalised SMS messages sent",
      step3: "7 emails drafted and sent via SMTP",
      step4: "Voice confirmation sent ↓",
      resultLabel: "Result",
      resultText: "One command. Four actions. Voice confirmation delivered. All from a single Telegram chat.",
      voiceLabel: "AI Voice",
    },
    diff: {
      label: "Why MazoLogic", subLabel: "Agency-as-usual ↔ AI OS",
      h2a: "We don't sell", h2b: " projects", h2c: "We build", h2d: " operating systems",
      lead: "Most AI agencies ship a chatbot and walk away. We build the layer that runs your operations — and hand it over with documentation your team actually uses.",
      colOld: "Agency-as-usual",
      rows: [
        { label: "Scope",     old: "A chatbot bolted onto one form.",               new: "An AI OS running a whole business process." },
        { label: "Ownership", old: "Monthly SaaS rental. Leave, lose everything.",  new: "You own the system. Host where you choose." },
        { label: "Process",   old: "Generic assistant answering questions.",         new: "Process mapped first. Agent built second." },
        { label: "Delivery",  old: "A demo, then months of iteration.",              new: "Fixed scope. Measurable output. Handed off." },
      ],
    },
    footer: { privacy: "Privacy", terms: "Terms", contact: "Contact" },
  },

  pl: {
    nav: { method: "Metoda", process: "Proces", infra: "Dowolna infrastruktura", cta: "Umów bezpłatny audyt →" },
    hero: {
      eyebrow: "Bezpłatny · 30 minut · Zero zobowiązań",
      h1a: "Twoja firma żyje w 12 miejscach.",
      h1b: "Czas dać jej jeden głos.",
      sub: "CRM mówi jedno. Arkusz mówi co innego. Zespół pyta na Slacku. Nikt nie ma pełnego obrazu — i każda decyzja kosztuje czas.",
      h1variants: [
        { h1a: 'Twoja firma żyje w <span style="color:#6fa8d4">12 miejscach.</span>', h1b: "Czas dać jej jeden głos.", sub: "CRM mówi jedno. Arkusz mówi co innego. Zespół pyta na Slacku. Nikt nie ma pełnego obrazu — i każda decyzja kosztuje czas. Nie wyrzucamy Twojego stacku. Łączymy go, dajemy mu pamięć i pozwalamy Ci rozmawiać z całością naraz." },
        { h1a: 'Przestań szukać danych <span style="color:#6fa8d4">po narzędziach.</span>', h1b: "Zacznij rozmawiać z firmą.", sub: "Zostawiasz narzędzia które znasz. My dodajemy warstwę która sprawia, że mówią do siebie — i do Ciebie. Jedna rozmowa zastępuje osiem otwartych zakładek." },
        { h1a: 'Arkusze. Dashboardy. Wiadomości. <span style="color:#6fa8d4">Przeczucie.</span>', h1b: "Jest lepszy sposób prowadzenia firmy.", sub: "Te narzędzia nie są problemem. Problemy są w lukach między nimi. Wchodzimy na to co już masz — i wypełniamy każdą lukę automatyzacją." },
        { h1a: 'Twój zespół spędza godziny łącząc dane, <span style="color:#6fa8d4">które powinny łączyć się same.</span>', h1b: "My automatyzujemy połączenia. Ty prowadzisz firmę.", sub: "Dane już istnieją. Procesy już działają. Budujemy system który łączy je automatycznie — bez migracji, bez przestojów." },
        { h1a: 'Twoje procesy są rozproszone. <span style="color:#6fa8d4">Twoje dane milczą.</span>', h1b: "Naprawiamy jedno i drugie.", sub: "Nic nie zostaje wyrzucone. Wpinamy się w istniejący stack, ujednolicamy to co już tam jest i dajemy Ci jedno miejsce do zarządzania całością." },
      ],
      cta: "Umów bezpłatny audyt →",
      chip1: "Całkowicie bezpłatny", chip2: "Tylko 30 minut", chip3: "Dowiesz się gdzie AI zaoszczędzi Ci czas lub pieniądze",
      vp1: "Gdzie Twoja firma traci pieniądze",
      vp2: "Co najbardziej hamuje Twój wzrost",
      vp3: "Gotowy plan wdrożenia AI",
    },
    method: {
      eyebrow: "Jak działamy",
      h2a: "Nie dokładamy kolejnego narzędzia,", h2b: "tylko je dla Ciebie automatyzujemy.",
      lead: "Zaczynamy od zrozumienia jak dokładnie działa Twój biznes. Następnie budujemy inteligentny system, z którym możesz rozmawiać i który zarządza wszystkimi Twoimi procesami i narzędziami, które już masz.",
      card1h: "Mapujemy operacje", card1p: "Zaczynamy od ustrukturyzowanego audytu — nie założeń. Uczymy się jak Twój biznes naprawdę działa, rozpoznajemy powtarzalne i żmudne czynności oraz trudności w przepływie informacji, które można uprościć i rozwiązać łatwo z AI.", card1tag: "→ Audyt Architektury · Mapa procesów · Szacunek ROI",
      card2h: "Unifikujemy w jeden system", card2p: "Łączymy narzędzia, konsolidujemy dane i trenujemy AI na kontekście Twojego biznesu — klientach, historii, języku marki.", card2tag: "→ SSOT · Warstwa kontekstu · Agenci podłączeni do Twojego stosu",
      card3h: "Oddajemy kontrolę", card3p: "Jeden interfejs do prowadzenia operacji. Wydajesz polecenie, dostajesz wynik. Dashboardy dostępne na życzenie — żadnego ręcznego wpisywania.", card3tag: "→ Udokumentowany · Wytrenowany · Na zawsze Twój",
    },
    solution: {
      eyebrow: "Co dostajesz", h2a: "System zbudowany pod Twój biznes.", h2b: "Nie szablon. Nie chatbot.",
      card1h: "Jedno Źródło Prawdy", card1p: "Wszystkie dane firmy — klienci, przychody, projekty, historia — w jednym miejscu, z którego AI może faktycznie korzystać.", card1tag: "→ CRM · Baza danych · Czysta warstwa danych",
      card2h: "Agenci, którzy myślą", card2p: "Automatyzacje, które nie tylko 'triggerują' — rozumują. Zbudowane na Twoich zmapowanych procesach.", card2tag: "→ Telegram · Email · Raporty · Planowanie",
      card3h: "Dostarczone i udokumentowane", card3p: "Pełne przekazanie. Zespół wytrenowany, system udokumentowany, wszystko Twoje.", card3tag: "→ Wytrenowany · Udokumentowany · Twój",
    },
    spotlight: { left: "Gotowy na wdrożenie", right: "Systemu Operacyjnego AI?" },
    matrix: {
      eyebrow: "Audyt Architektury", h2a: "Zanim zbudujemy:", h2b: "jasny obraz tego, co warto automatyzować.",
      lead: "Mapujemy Twoje operacje na cztery strefy — według kosztu, nakładu i zwrotu.",
      axisHigh: "Wysoki wpływ", axisLow: "Niski wpływ", axisEffortLow: "Niski nakład →", axisEffortHigh: "Wysoki nakład",
      q1tag: "Szybkie wygrane", q1title: "Szybkie wygrane", q1desc: "Szybki odzysk czasu. Wdrożenie 2–3 tyg., zwrot mierzalny do 4. tygodnia.", q1foot: "01 · zacznij tu",
      q2tag: "Strategiczne", q2title: "Rdzeń AI OS", q2desc: "Systemy o wysokiej dźwigni. Fundament, na którym stoi reszta biznesu.", q2foot: "02 · rdzeń AI OS",
      q3tag: "Uzupełnienia", q3title: "Później", q3desc: "Drobne zadania powtarzalne. Warte automatyzacji gdy rdzeń jest stabilny.",
      q4tag: "Unikaj", q4title: "Odłóż", q4desc: "Dużo pracy, mały zwrot. Udokumentuj, zaparkuj, wróć później.",
    },
    process: {
      eyebrow: "Mapa wdrożenia", h2a: "Cztery fazy.", h2b: "Od audytu po przekazanie.",
      phases: [
        { num: "PHASE 01", h: "Audyt",       p: "Ustrukturyzowana sesja 30 minut dla MŚP lub 1–2 dni on-site dla większych firm." },
        { num: "PHASE 02", h: "Budowanie",   p: "Łączymy źródła danych, czyścimy warstwę informacji i trenujemy AI na kontekście Twojego biznesu." },
        { num: "PHASE 03", h: "Kalibracja",  p: "14-dniowa kalibracja na żywo. Monitorujemy każde działanie i doprowadzamy dokładność powyżej 95%." },
        { num: "PHASE 04", h: "Przekazanie", p: "Pełny transfer: wytrenowany system AI, kompletna dokumentacja i sesja wdrożeniowa." },
      ],
    },
    infra: {
      eyebrow: "Dowolna infrastruktura", h2a: "Twój stack zostaje.", h2b: "My budujemy na nim.",
      lead: "Nie musisz rezygnować z CRM-a, arkuszy ani narzędzi, których używasz. AI OS wdrażamy jako nakładkę na to, co już masz.",
    },
    scorecard: { eyebrow: "Diagnostyka Operacyjna", h2a: "Gdzie Twoja firma traci czas", h2b: "i co mogłoby działać lepiej?", lead: "15 pytań. Pokażemy Ci dokładnie gdzie AI ma sens — i gdzie nie." },
    gate: { title: "Gdzie wysłać Twoje wyniki?", sub: "Wyślemy Ci e-mailem spersonalizowaną mapę wdrożenia AI na podstawie Twoich odpowiedzi.", name: "Twoje imię", email: "Służbowy email", cta: "Umów bezpłatny audyt →", privacy: "Zero spamu. Wyniki zostają prywatne. Wypisz się w każdej chwili." },
    q:   { no: "Nie — wszystko jest w głowach ludzi", partial: "Częściowo — niektóre rzeczy są spisane", yes: "Tak — większość procesów jest udokumentowana" },
    q1:  { q: "Czy Twoja firma ma udokumentowane, powtarzalne procesy dla rutynowych zadań?" },
    q2:  { q: "Czy dane firmy są scentralizowane w jednym systemie?", a: "Nie — dane żyją w emailach, arkuszach i wiadomościach", b: "Częściowo — mamy CRM, ale nie jest konsekwentnie używany", c: "Tak — mamy centralny system, którego używa cały zespół" },
    q3:  { q: "Czy jakiekolwiek powtarzalne zadania administracyjne są zautomatyzowane?", a: "Nie — wszystko robimy ręcznie", b: "Niektóre — używamy prostych narzędzi jak Zapier", c: "Tak — wiele workflow jest zautomatyzowanych" },
    q4:  { q: "Czy Twój zespół regularnie używa narzędzi AI w codziennej pracy?", a: "Nie — AI nie jest jeszcze częścią naszego workflow", b: "Sporadycznie — kilka osób używa od czasu do czasu", c: "Tak — AI jest regularną częścią naszej pracy" },
    q5:  { q: "Czy firma używa zunifikowanej platformy komunikacyjnej?", a: "Nie — polegamy na emailach i telefonach", b: "Używamy aplikacji, ale nie konsekwentnie", c: "Tak — mamy zunifikowaną platformę" },
    q6:  { q: "Czy istnieje system który automatycznie follow-upuje z leadami lub klientami?", a: "Nie — follow-upy zależą od pamięci", b: "Podstawowo — kilka przypomnień ustawionych ręcznie", c: "Tak — follow-upy są zautomatyzowane" },
    q7:  { q: "Czy możesz uzyskać klarowny raport o wynikach biznesu bez ręcznego pobierania danych?", a: "Nie — budujemy raporty ręcznie", b: "Częściowo — część danych jest automatyczna", c: "Tak — dashboardy aktualizują się automatycznie" },
    q8:  { q: "Czy firma ma udokumentowane polityki dotyczące prywatności danych?", a: "Nie — nie istnieją formalne polityki", b: "Nieformalnie — są niepisane zasady", c: "Tak — formalne polityki są na miejscu" },
    q9:  { q: "Czy Twoja firma ma jasny plan gdzie AI powinno być wdrożone w ciągu 12 miesięcy?", a: "Nie — reagujemy gdy pojawia się AI", b: "Luźno — mamy pomysły, ale nic nie jest udokumentowane", c: "Tak — mamy udokumentowaną mapę drogową AI" },
    q10: { q: "Czy jest dedykowany budżet przeznaczony na wdrożenie AI?", a: "Nie — żaden budżet na to nie istnieje", b: "Płacimy za niektóre narzędzia SaaS, ale bez dedykowanego budżetu AI", c: "Tak — mamy dedykowany budżet na AI" },
    q11: { q: "Który opis najlepiej pasuje do Twojego obecnego poziomu adopcji AI?", a: "Nie zaczęliśmy — AI jest ciągle na liście 'do zbadania'", b: "Eksperymentujemy — próbowaliśmy niektórych narzędzi", c: "Wdrażamy — AI jest w użyciu, ale nie głęboko zintegrowane" },
    q12: { q: "Jaki jest Twój główny cel na najbliższe 90 dni?", a: "Zaoszczędzić 10+ godzin czasu zespołu tygodniowo", b: "Zwiększyć liczbę leadów i zamknąć więcej transakcji", c: "Zmniejszyć błędy i ręczne wprowadzanie danych", d: "Zbudować przewagę konkurencyjną AI w mojej branży" },
    q13: { q: "Co najbardziej powstrzymuje Cię teraz od skalowania AI?", a: "Złożoność techniczna — nie wiem od czego zacząć", b: "Czas — brak mocy do badania i wdrożenia", c: "Obawy o budżet — niejasne czy ROI jest realne", d: "Znalezienie właściwego partnera który naprawdę dostarcza" },
    q14: { q: "Które rozwiązanie najbardziej Ci odpowiada?", a: "Zrób-sam — chcę szkolenie do samodzielnego budowania", b: "Prowadzony — chcę konsultanta który pomoże mi skonfigurować narzędzia", c: "Zrób-za-mnie — chcę kompletny AI OS zbudowany i wdrożony" },
    q15: { q: "Czy jest coś specyficznego o Twojej firmie co powinniśmy wiedzieć? (opcjonalne)", cta: "Umów bezpłatny audyt →" },
    results: { insightsTitle: "Twoje spersonalizowane spostrzeżenia" },
    caseStudy: {
      eyebrow: "Na żywo · Wdrożony · Działa",
      h2a: "Jeden agent.", h2b: "Jeden OS. 19 narzędzi.",
      h3a: "Właściciel pisze jedno zdanie.", h3b: "System zajmuje się resztą.",
      p: "Agent AI z 19 narzędziami — podłączony do Airtable CRM, emaila, wiadomości głosowych i web scrapingu.",
      stat1label: "połączonych narzędzi", statSwitch: "przełączania aplikacji",
      demoLabel: "Interakcja na żywo — Telegram",
      ownerMsg: "Znajdź w bazie danych potencjalnych kupców na nieruchomość na ulicy Kwiatowej. Wyślij do wszystkich SMS-a, że jest nowa nieruchomość spełniająca ich kryteria. Wyślij też do nich e-maila. Na koniec potwierdź mi głosówką na Telegramie, że wszystko wykonałeś.",
      step1: "Przeszukano Airtable — 7 pasujących kupców",
      step2: "7 spersonalizowanych SMS-ów wysłanych",
      step3: "7 e-maili zredagowanych i wysłanych przez SMTP",
      step4: "Głosowe potwierdzenie odesłane ↓",
      resultLabel: "Wynik",
      resultText: "Jedno polecenie. Cztery akcje. Głosowe potwierdzenie dostarczone. Wszystko z jednego czatu na Telegramie.",
      voiceLabel: "Głos AI",
    },
    diff: {
      label: "Dlaczego MazoLogic", subLabel: "Agencja klasyczna ↔ AI OS",
      h2a: "Nie sprzedajemy", h2b: " projektów", h2c: "Budujemy", h2d: " systemy operacyjne",
      lead: "Większość agencji AI dostarcza chatbota i znika. My budujemy warstwę która zarządza operacjami — i przekazujemy ją z dokumentacją którą Twój zespół naprawdę użyje od pierwszego dnia.",
      colOld: "Agencja klasyczna",
      rows: [
        { label: "Zakres",   old: "Chatbot przyklejony do formularza.",              new: "AI OS zarządzający całym procesem biznesowym." },
        { label: "Własność", old: "Miesięczny abonament. Odejdziesz — stracisz wszystko.", new: "Cała wiedza i pamięć systemu zapisana w plikach — Twoich na zawsze." },
        { label: "Proces",   old: "Generyczne narzędzie wrzucone w workflow.",        new: "Najpierw mapujemy procesy, potem budujemy rozwiązania szyte na miarę Twojego biznesu." },
        { label: "Dostawa",  old: "Demo, potem miesiące otwartych iteracji.",         new: "Jasny zakres. Wdrożenie. Ulepszenia w ramach procesu." },
      ],
    },
    footer: { privacy: "Prywatność", terms: "Regulamin", contact: "Kontakt" },
  },
} as const;

export type Lang = "en" | "pl";
